travis:
  secure:
    BINSTAR_TOKEN: KlaxCNl08KHQVFYByPyPj3ErJBcmwmCBtNK28bRLQ7riyx+vVhRQ8WcahLzwG7UGzGHFR67MYJy9/yu1OuqXW72aqlHzHSvZZr+2Pu3qh/hgdAGcilmke5xbAA1dGVKiK7crOGoJ3DsecK2F5ZFJjbTeIyMhgKrHuefylZkj+LZFJWXs584GHnza7BwEYvS/L3JcOCAfQgM5Z0Qz3q/NsL1LR2Y4e+V4Z95lxZajmRuym/j6+rsKrAsWexBNnPpuPBShPPkxDREotnxpmiPYjiH5r2Rv0s9E4ISOXsYnbUT9OhvCVMCTr3kXQFsZkgnvxHrctmjOUyc546cPBlm/DSVqXTMqZMsk1I6p8C9lNiKcJekQPkp/jdiupjM2dTZ+LJ39NGKQNgHdvQRpaKbd46Wi2Y9tevdP9+S+Ng/Mp6RR2BxSUC/X11vQprYBdtzL/UNeCA5ZCLpIH3SbimBrYDDGRqdroaosLR0sKsGDcxO2ESVEV+PDn96zkS8S2a0ySQ/KBkdHphfo+zQFHz4XphH22GRn8TVEa5+VzaOUPHd+hwBtZsS/kXKXy2T/0rsO9F1lCMRgvMcamxG3N0AEAATwQ9AyggGsW//NAWL/fbYzpwvTfaGKS9+qLOhkQAO3ZDXVsxHlKmu2O9uK2DE9q+N7gYGYZAz/yVKYuaXdfRk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
