travis:
  secure:
    BINSTAR_TOKEN: VDcZoOukv6s6zhi1fV8502V31rg0Nr2ce2/r0UpOivD3fswJECx8CDkHgIlXIQk7wu9zi6gR8zz28lk6Txak8JGjC1J8noHeov5E0Z5SR+8Q34kfnxo7RZn6MlktFvaZA93j8Po1psu0EapBeEcpGt9O16+soqOs2m4rFf66aJmXYM1kAYd/lfjgHAFJ4/O/tV/BfD06gToJx67uD/MtSntflZEFvmgj1oag29Klzi66kA/9feWHi4+d2uH/aDwk6GcxjULAcIKPddeqsMZHeYtZgfGAQnBDFmLloOmiRC9qWwvGsYW/aeJTkDgHX0VmoI7OJ0FWeokLAemOVe9NavW4OkvjWNF9Oqe3yxnYGKHjm1MeRO/WjGf/EjFEUPIBIoO8UG/fP7N2LS0LAIy8N4YP9NPSg7tmg/3fmiAcqVvrY8wGP9XYWyAWiDNUmGhwDAyWLBXwzRxh1KcHPtzLj/4nkX6fiMJJbApNrMXuMvzDYY9iGl2BGpYp8dMAT64SQjyBDrXGiMOTFKcYib18FK9Mtj3q3zEvgK3GbL63077X6qwLhP79ZVD8SbL29IEQ9qzGNski7EtIl9kFoosNwctQi5zcO/uR6r7qLrZjP0Wo+zblJAqU+std+KJO7QdXwUjOxsQt2BNksDvtenmRFSIQ/q/R1fLhb06slgUiSB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
